app.py
import os
from flask import Flask
from routes import pages
from pymongo import MongoClient
from dotenv import load_dotenv

load_dotenv()

def create_app():
    app= Flask(__name__)
    client = MongoClient(os.environ.get("MONGODB_URL"))
    app.db = client.get_default_database()
    

    app.register_blueprint(pages)
    return app

routes.py
from flask import current_app, Blueprint, render_template, request, redirect, url_for
import datetime
import uuid

pages = Blueprint("tasks", __name__, template_folder="templates", static_folder="Static")


@pages.context_processor
def addCalcDateRnge():
    def dateRange(start: datetime.datetime):
        dates = [start + datetime.timedelta(days=diff)
                 for diff in range(-3, 4)]
        return dates
    return {"dateRange": dateRange}


def todayMidnight():
    today = datetime.datetime.today()
    return datetime.datetime(today.year, today.month, today.day)


def Cday():
    return datetime.datetime.today()


@pages.route("/", methods=["GET", "POST"])
def index():
    dateStr = request.args.get("date")
    if dateStr:
        selectedDate = datetime.datetime.fromisoformat(dateStr)
    else:
        selectedDate = todayMidnight()

    today = todayMidnight()
    if request.method == "POST":
        data = request.form.get("task")
        if (data):
            if( len(list(current_app.db.tasks.find({"name" : data}))) == 0 ):
                current_app.db.tasks.insert_one(
                    {"_id": uuid.uuid4().hex, "added": today, "name": data}
                )

    tasksOnDay = current_app.db.tasks.find({"added" : {"$lte" : selectedDate}})
    completions = [
        taskD["name"]
        for taskD in current_app.db.completions.find({"date" : {"$eq" : selectedDate}})
    ]

    return render_template("index.html", tasks=tasksOnDay, title="Task Tracker - Home",
                           selectedDate=selectedDate, completions=completions, CurrentDay=Cday())


@pages.route("/add", methods=["GET", "POST"])
def addTask():
    today = todayMidnight()
    return render_template("addTask.html", title="Task Tracker - Add Task",
                           CurrentDay=Cday(), selectedDate=today)


@pages.route("/complete", methods=["POST"])
def complete():
    dateStr = request.form.get("date")
    task = request.form.get("taskName")
    date = datetime.datetime.fromisoformat(dateStr)
    current_app.db.completions.insert_one({"date": date, "name": task})
    current_app.db.tasks.delete_one({"name": task})

    return redirect(url_for("tasks.index", date=date))

templates/addTask.html
{% extends "layout.html" %} {% block mainContent %}
<div >
<form class="form" method="POST" action = "{{ url_for('tasks.index') }}" >
    <textarea
      class="formInput"
      id="task"
      name="task"
      rows="3"
      placeholder=" Add a new task..."
    ></textarea>
    <button class="formButton" type="submit" id="submit" >
            Add
    </button>
  </form>
</div> 
{% endblock %}

templates/index.html
{% extends "layout.html" %} {% block mainContent %}
<section class="TasktList">
  {% for task in completions %}  
  <div class="task">
    <p class="taskName">{{ task }}</p>
    <svg
      class="taskIcon"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 20 20"
      fill="currentColor"
    >
      <path
        fill-rule="evenodd"
        d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
        clip-rule="evenodd"
      />
    </svg>
  </div>
  {% endfor %}
  {% for task in tasks %}
  <div class="task">
    <form method="POST" class="taskForm" action="{{ url_for('tasks.complete') }}">
      <input
        type="hidden"
        id="taskId"
        name="taskName"
        value="{{ task['name'] }}"
      />
      <input type="hidden" id="date" name="date" value="{{ selectedDate }}" />
      <button type="submit" class="taskButton">{{ task["name"] }}</button>
    </form>
  </div>
  {% endfor %}
</section>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="icon"  type="image/png/svg"  href="/static/DALL·E 2023-01-20 22.43.52 - logo for task tracker.png" />
    <title>
      {{ title }}</title>
      <link
      href="https://fonts.googleapis.com/css2?family=Inter&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="/static/css/main.css" />

    {% block head_content %} {% endblock %}
  </head>

  <body>
    <header class="header">
      <h1 class="headerLogo">
        <a href="{{ url_for('tasks.index') }}" class="headerLink"> Tasks</a>
      </h1>
      <a class="today" href="{{ url_for('tasks.index') }}"> <div class ="todayDate"> 
        Today  {{CurrentDay.strftime("%d")}}
      </div>
    </a>
      {% if "add" not in request.endpoint %}
      <a href="{{ url_for('tasks.addTask') }}" class="headerLink">+ Add new Task</a>
      {% endif %}
    </header>

    <main class="main">
      <section class="dates" dates>
        {% for date in dateRange(selectedDate) %}
        <a
          class="dateLink {{'dateLinkCurrent' if loop.index0 == 3 else ''}}"
          href="{{ url_for('tasks.index', date=date)}}"
        >
          <time class="date" datetime="{{date}}">
            <span>{{date.strftime("%a")}}</span>
            <span>{{date.strftime("%d")}}</span>
            
          </time>
        </a>
        {% endfor %}
      </section>
      {% block mainContent %} {% endblock %}
    </main>
  </body>
</html>